import Joi from 'joi';

export const appConfigSchema = Joi.object({
  DB_HOST: Joi.string().default('localhost'),
  DB_PORT: Joi.number().default(5434),
  DB_USER: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  DB_DATABASE: Joi.string().required(),
  MONGO_URI: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  JWT_SECRET_2: Joi.string().required(),
  JWT_EXPIRES_IN: Joi.string().required(),
  JWT_EXPIRES_IN_2: Joi.string().required(),
  CORS_ORIGIN: Joi.string().required(),
  MAIL_HOST: Joi.string().required(),
  MAIL_PORT: Joi.number().required(),
  MAIL_SECURE: Joi.string().valid('true', 'false').required(),
  MAIL_USER: Joi.string().required(),
  MAIL_PASS: Joi.string().required(),
  MAIL_FROM: Joi.string().required(),
  APP_NAME: Joi.string().required(),
  APP_DESCRIPTION: Joi.string().required(),
  APP_VERSION: Joi.string().required(),
  FE_URL: Joi.string().required(),
  NODE_ENV: Joi.string().required(),
  API_PORT: Joi.number().required(),
});
